In [ ]:
#imports 
import csv 
import math
import pandas as pd
import numpy as np
import json
import ast

import psycopg2

In [ ]:
def my_select_query_pandas(query, rollback_before_flag, rollback_after_flag):
    "function to run a select query and return rows in a pandas dataframe"
    
    if rollback_before_flag:
        connection.rollback()
    
    df = pd.read_sql_query(query, connection)
    
    if rollback_after_flag:
        connection.rollback()
    
    # fix the float columns that really should be integers
    
    for column in df:
    
        if df[column].dtype == "float64":

            fraction_flag = False

            for value in df[column].values:
                
                if not np.isnan(value):
                    if value - math.floor(value) != 0:
                        fraction_flag = True

            if not fraction_flag:
                df[column] = df[column].astype('Int64')
    
    return(df)

In [ ]:
connection = psycopg2.connect(
    user = "postgres",
    password = "ucb",
    host = "postgres",
    port = "5432",
    database = "postgres"
)

cursor = connection.cursor()

In [ ]:
def my_read_csv_file(file_name, limit):
    "read the csv file and print only the first limit rows"
    
    csv_file = open(file_name, "r")
    
    csv_data = csv.reader(csv_file)
    
    i = 0
    
    for row in csv_data:
        i += 1
        if i <= limit:
            print(row)
            
    print("\nPrinted ", min(limit, i), "lines of ", i, "total lines.")

In [ ]:
connection.rollback()

query = """

drop table if exists movies

"""

cursor.execute(query)

connection.commit()

# Maybe make this a stage 1 table

In [ ]:
connection.rollback()

query = """

create table movies (
    index varchar(4802),
    budget varchar(4802),
    genres varchar(4802),
    homepage varchar(4802),
    id varchar(4802),
    keywords varchar(4802),
    original_language varchar(4802),
    original_title varchar(4802),
    overview varchar(4802),
    popularity varchar(4802),
    production_companies text,
    production_countries text,
    release_date varchar(4802),
    revenue varchar(4802),
    runtime varchar(4802),
    spoken_languages text,
    status varchar(4802),
    tagline varchar(4802),
    title varchar(4802),
    vote_average varchar(4802),
    vote_count varchar(4802),
    cast_ varchar(4802),
    crew_ text,
    director_ varchar(4802)    
)

"""

cursor.execute(query)

connection.commit()

In [ ]:
my_read_csv_file("/user/projects/project-3-richardshelby/data/raw/movies.csv", limit = 10)

In [ ]:
connection.rollback()

query = """

copy movies
from '/user/projects/project-3-richardshelby/data/raw/movies.csv' delimiter ',' NULL '' csv header;

"""

cursor.execute(query)

connection.commit()

In [185]:
rollback_before_flag = True
rollback_after_flag = True

query = """

select * 
from movies
where (budget <> '0') and (budget <> '') and (genres <> '') and (revenue <> '0') and (revenue <> '') 
       and (vote_count <> '0') and (vote_count <> '') and (director_ <> '') and (cast_ <> '') 
       and (release_date <> '') and (runtime <> '0') and (runtime <> '') 

"""

my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast_,crew_,director_
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.37678799999999,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.31295,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3218,4773,27000,Comedy,http://www.miramax.com/movie/clerks/,2292,salesclerk loser aftercreditsstinger,en,Clerks,Convenience and video store clerks Dante and R...,19.748658,...,92.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Just because they serve you doesn't mean they ...,Clerks,7.4,755,Brian O'Halloran Jeff Anderson Jason Mewes Kev...,"[{'name': 'Kevin Smith', 'gender': 2, 'departm...",Kevin Smith
3219,4788,12000,Horror Comedy Crime,None,692,gay trailer park pop culture drug dealer heroin,en,Pink Flamingos,Notorious Baltimore criminal and underground f...,4.553644,...,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,An exercise in poor taste.,Pink Flamingos,6.2,110,Divine David Lochary Mary Vivian Pearce Mink S...,"[{'name': 'John Waters', 'gender': 2, 'departm...",John Waters
3220,4792,20000,Crime Horror Mystery Thriller,None,36095,japan prostitute hotel based on novel hallucin...,ja,キュア,A wave of gruesome murders is sweeping Tokyo. ...,0.212443,...,111.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Madness. Terror. Murder.,Cure,7.4,63,Koji Yakusho Masato Hagiwara Tsuyoshi Ujiki An...,"[{'name': 'Kiyoshi Kurosawa', 'gender': 2, 'de...",Kiyoshi Kurosawa
3221,4796,7000,Science Fiction Drama Thriller,http://www.primermovie.com,14337,distrust garage identity crisis time travel ti...,en,Primer,Friends/fledgling entrepreneurs invent a devic...,23.307949,...,77.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,What happens if it actually works?,Primer,6.9,658,Shane Carruth David Sullivan Casey Gooden Anan...,"[{'name': 'Shane Carruth', 'gender': 2, 'depar...",Shane Carruth
3222,4798,220000,Action Crime Thriller,None,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez

In [184]:
rollback_before_flag = True
rollback_after_flag = True

query = """

select * 
from movies
where (budget <> '0') and (budget <> '') and (genres <> '') and (revenue <> '0') and (revenue <> '') 
       and (vote_count <> '0') and (vote_count <> '') and (director_ <> '') and (cast_ <> '') 
       and (release_date <> '') and (runtime <> '0') and (runtime <> '') 

"""

moviedf = my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

# Data Cleaning
1. remove missing or zero values from budget
2. remove missing values from genre
3. remove missing or zero values from revenue
4. remove missing or zero values from vote_count
5. remove missing or zero values from directors 
6. remove missing values from release_date
7. remove missing from cast
8. remove missing or zero values from runtime

In [ ]:
len(moviedf)

In [ ]:
moviedf2 = moviedf[pd.isna(moviedf['budget']) == False]
moviedf2 = moviedf2[moviedf2['budget'] != '0']
len(moviedf2)

In [ ]:
moviedf3 = moviedf2[pd.isna(moviedf2['genres']) == False]
len(moviedf3)

In [ ]:
moviedf4 = moviedf3[pd.isna(moviedf3['revenue']) == False]
moviedf4 = moviedf3[moviedf3['revenue'] != '0']
len(moviedf4)

In [ ]:
moviedf5 = moviedf4[pd.isna(moviedf4['vote_count']) == False]
moviedf5 = moviedf4[moviedf4['vote_count'] != '0']
len(moviedf5)

In [ ]:
moviedf6 = moviedf5[pd.isna(moviedf5['director_']) == False]
len(moviedf6)

In [ ]:
moviedf7 = moviedf6[pd.isna(moviedf6['cast_']) == False]
len(moviedf7)

In [ ]:
moviedf8 = moviedf7[pd.isna(moviedf7['release_date']) == False]
len(moviedf8)

In [ ]:
moviedf9 = moviedf8[pd.isna(moviedf8['runtime']) == False]
moviedf9 = moviedf8[moviedf8['runtime'] != '0']
len(moviedf9)

In [ ]:
moviedf9

# Convert key-value list columns using ast library
https://www.geeksforgeeks.org/python/python-convert-string-dictionary-to-dictionary/

**I am doing this assuming keys are standardized across rows (for each column)**

In [ ]:
crewdict = ast.literal_eval(moviedf['crew_'][502][1:-1])
crewdict[0].keys()

In [ ]:
pcompdict = ast.literal_eval(moviedf['production_companies'][0][1:-1])
pcompdict[1].keys()

In [ ]:
pcontdict = ast.literal_eval(moviedf['production_countries'][1][1:-1])
pcontdict.keys()

In [ ]:
sldict = ast.literal_eval(moviedf['spoken_languages'][1][1:-1])
sldict.keys()

In [ ]:
#crewdict = ast.literal_eval(moviedf['crew_'][1][1:-1])
#crewdict

kvcols = ['production_companies','production_countries','spoken_languages','crew_']

#crewdict[1].keys()

prodcomps = []
prodcountries = []
spokenlangs = []
crew = []

for m in range(len(moviedf)):
    
    currmov = moviedf['title'][m]
    
    if len(moviedf['crew_'][m]) > 0:
        
        if moviedf['crew_'][m] != '[]':
    
            currnesteddict_crew = ast.literal_eval(moviedf['crew_'][m][1:-1])

            for c in currnesteddict_crew:

                crewmat = {}

                if c == 'name':
                    crewmat['name'] = currnesteddict_crew['name']
                    crewmat['gender'] = currnesteddict_crew['gender']
                    crewmat['department']  = currnesteddict_crew['department']
                    crewmat['job'] = currnesteddict_crew['job']
                    crewmat['credit_id'] = currnesteddict_crew['credit_id']
                    crewmat['id'] = currnesteddict_crew['id']
                    crewmat['movie'] = currmov
                    crew.append(crewmat)
                    break
                else:
                    crewmat['name'] = c['name']
                    crewmat['gender'] = c['gender']
                    crewmat['department']  = c['department']
                    crewmat['job'] = c['job']
                    crewmat['credit_id'] = c['credit_id']
                    crewmat['id'] = c['id']
                    crewmat['movie'] = currmov
                    crew.append(crewmat)
        else:
            crewmat = {}
            crewmat['name'] = []
            crewmat['gender'] = []
            crewmat['department']  = []
            crewmat['job'] = []
            crewmat['credit_id'] = []
            crewmat['id'] = []
            crewmat['movie'] = currmov 
            
            crew.append(crewmat)
    else:
            crewmat = {}
            crewmat['name'] = []
            crewmat['gender'] = []
            crewmat['department']  = []
            crewmat['job'] = []
            crewmat['credit_id'] = []
            crewmat['id'] = []
            crewmat['movie'] = currmov 
            
            crew.append(crewmat)
            
    if len(moviedf['production_companies'][m]) > 0:
        
        if moviedf['production_companies'][m] != '[]':
    
            currnesteddict_comp = ast.literal_eval(moviedf['production_companies'][m][1:-1])

            for p in currnesteddict_comp:

                pcompmat = {}

                if p == 'name':
                    pcompmat['name'] = currnesteddict_comp['name']
                    pcompmat['id'] = currnesteddict_comp['id']
                    pcompmat['movie'] = currmov
                    prodcomps.append(pcompmat)
                    break
                else:
                    pcompmat['name'] = p['name']
                    pcompmat['id'] = p['id']
                    pcompmat['movie'] = currmov
                    prodcomps.append(pcompmat)
        else:
            pcompmat = {}
            pcompmat['name'] = []
            pcompmat['id'] = []
            pcompmat['movie'] = currmov 
            
            prodcomps.append(pcompmat)
    else:
            pcompmat = {}
            pcompmat['name'] = []
            pcompmat['id'] = []
            pcompmat['movie'] = currmov 
            
            prodcomps.append(pcompmat)
    
    if len(moviedf['production_countries'][m]) > 0:
        
        if moviedf['production_countries'][m] != '[]':
    
            currnesteddict_cont = ast.literal_eval(moviedf['production_countries'][m][1:-1])

            for pc in currnesteddict_cont:

                pcontmat = {}

                if pc == 'iso_3166_1':
                    pcontmat['iso_3166_1'] = currnesteddict_cont['iso_3166_1']
                    pcontmat['name'] = currnesteddict_cont['name']
                    pcontmat['movie'] = currmov
                    prodcountries.append(pcontmat)
                    break
                else:
                    pcontmat['iso_3166_1'] = pc['iso_3166_1']
                    pcontmat['name'] = pc['name']
                    pcontmat['movie'] = currmov
                    prodcountries.append(pcontmat)
        else:
            pcontmat = {}
            pcontmat['iso_3166_1'] = []
            pcontmat['name'] = []
            pcontmat['movie'] = currmov 
            
            prodcountries.append(pcontmat)
    else:
            pcontmat = {}
            pcontmat['iso_3166_1'] = []
            pcontmat['name'] = []
            pcontmat['movie'] = currmov 
            
            prodcountries.append(pcontmat)
            
    if len(moviedf['spoken_languages'][m]) > 0:
        
        if moviedf['spoken_languages'][m] != '[]':
    
            currnesteddict_sp = ast.literal_eval(moviedf['spoken_languages'][m][1:-1])

            for sp in currnesteddict_sp:

                spmat = {}

                if sp == 'iso_639_1':
                    spmat['iso_639_1'] = currnesteddict_sp['iso_639_1']
                    spmat['name'] = currnesteddict_sp['name']
                    spmat['movie'] = currmov
                    spokenlangs.append(spmat)
                    break
                else:
                    spmat['iso_639_1'] = sp['iso_639_1']
                    spmat['name'] = sp['name']
                    spmat['movie'] = currmov
                    spokenlangs.append(spmat)
        else:
            spmat = {}
            spmat['iso_639_1'] = []
            spmat['name'] = []
            spmat['movie'] = currmov 
            
            spokenlangs.append(spmat)
    else:
            spmat = {}
            spmat['iso_639_1'] = []
            spmat['name'] = []
            spmat['movie'] = currmov 
            
            spokenlangs.append(spmat)

In [ ]:
moviedf.keys()

In [ ]:
f = open("/user/projects/project-3-richardshelby/data/raw/crew.csv", "w")
dw = csv.DictWriter(f, crew[0].keys())
dw.writeheader()
dw.writerows(crew)
f.close()

f = open("/user/projects/project-3-richardshelby/data/raw/prodcomps.csv", "w")
dw = csv.DictWriter(f, prodcomps[0].keys())
dw.writeheader()
dw.writerows(prodcomps)
f.close()

f = open("/user/projects/project-3-richardshelby/data/raw/prodcountries.csv", "w")
dw = csv.DictWriter(f, prodcountries[0].keys())
dw.writeheader()
dw.writerows(prodcountries)
f.close()

f = open("/user/projects/project-3-richardshelby/data/raw/spokenlangs.csv", "w")
dw = csv.DictWriter(f, spokenlangs[0].keys())
dw.writeheader()
dw.writerows(spokenlangs)
f.close()

In [ ]:
connection.rollback()

query = """

drop table if exists crews

"""

cursor.execute(query)

connection.commit()

In [ ]:
connection.rollback()

query = """

create table crews (
    name varchar(130000),
    gender varchar(130000),
    department varchar(130000),
    job varchar(130000),
    credit_id varchar(130000),
    id varchar(130000),
    movie varchar(130000)
)

"""

cursor.execute(query)

connection.commit()

In [ ]:
connection.rollback()

query = """

copy crews
from '/user/projects/project-3-richardshelby/data/raw/crew.csv' delimiter ',' NULL '' csv header;

"""

cursor.execute(query)

connection.commit()

In [181]:
rollback_before_flag = True
rollback_after_flag = True

query = """

    select *
    from crews


"""

my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

,name,gender,department,job,credit_id,id,movie
0,Stephen E. Rivkin,0,Editing,Editor,52fe48009251416c750aca23,1721,Avatar
1,Rick Carter,2,Art,Production Design,539c47ecc3a36810e3001f87,496,Avatar
2,Christopher Boyes,0,Sound,Sound Designer,54491c89c3a3680fb4001cf7,900,Avatar
3,Christopher Boyes,0,Sound,Supervising Sound Editor,54491cb70e0a267480001bd0,900,Avatar
4,Mali Finn,1,Production,Casting,539c4a4cc3a36810c9002101,1262,Avatar
...,...,...,...,...,...,...,...
129604,Clark Peterson,2,Production,Executive Producer,58ce021b9251415a390165d9,6888,My Date with Drew
129605,Andrew Reimer,2,Production,Executive Producer,58ce0232c3a36850e90157da,61051,My Date with Drew
129606,Brian Herzlinger,2,Directing,Director,52fe44e8c3a368484e03da8d,85563,My Date with Drew
129607,Jon Gunn,2,Directing,Director,52fe44e8c3a368484e03da87,94471,My Date with Drew
129608,Brett Winn,0,Directing,Director,52fe44e8c3a368484e03da97,997560,My Date with Drew

In [ ]:
rollback_before_flag = True
rollback_after_flag = True

query = """
with 

ep as (
    select array_agg(name) as executive_producer,
           movie
    from crews
    where department = 'Production' and job = 'Executive Producer'
    group by movie
    order by movie),

cp as (
    select array_agg(name) as original_composer,
           movie
    from crews
    where department = 'Sound' and job = 'Original Music Composer'
    group by movie
    order by movie),

w as (
    select array_agg(name) as writer,
           movie
    from crews
    where department = 'Writing' and job = 'Writer'
    group by movie
    order by movie),

dp as (
    select array_agg(name) as director_photography,
           movie
    from crews
    where department = 'Camera' and job = 'Director of Photography'
    group by movie
    order by movie),

m as (
    select * 
    from movies
    where (budget <> '0') and (budget <> '') and (genres <> '') and (revenue <> '0') and (revenue <> '') 
           and (vote_count <> '0') and (vote_count <> '') and (director_ <> '') and (cast_ <> '') 
           and (release_date <> '') and (runtime <> '0') and (runtime <> '') 
)

select m.title as title,
       m.budget::numeric as budget,
       m.genres as genres,
       m.id as id,
       m.keywords as keywords,
       m.overview as overview,
       m.popularity::numeric as popularity,
       m.vote_average::numeric as vote_average,
       m.vote_count::numeric as vote_count,
       m.cast_ as cast,
       m.director_ as director,
       ep.executive_producer as executive_producer,
       w.writer as writer, 
       cp.original_composer as original_music_composer,
       dp.director_photography as director_photography
       
from m
left join ep 
    on m.title = ep.movie
left join w 
    on m.title = w.movie
left join cp 
    on m.title = cp.movie
left join dp 
    on m.title = dp.movie

"""

my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

In [ ]:
connection.rollback()

query = """

drop table if exists prod_country

"""

cursor.execute(query)

connection.commit()

In [ ]:
connection.rollback()

query = """

create table prod_country (
    iso_3166_1 varchar(7000),
    name varchar(7000),
    movie varchar(7000)
)

"""

cursor.execute(query)

connection.commit()

In [ ]:
connection.rollback()

query = """

copy prod_country
from '/user/projects/project-3-richardshelby/data/raw/prodcountries.csv' delimiter ',' NULL '' csv header;

"""

cursor.execute(query)

connection.commit()

In [ ]:
rollback_before_flag = True
rollback_after_flag = True

query = """

select *
from prod_country

"""

my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

In [ ]:
connection.rollback()

query = """

drop table if exists prod_company

"""

cursor.execute(query)

connection.commit()

In [ ]:
connection.rollback()

query = """

create table prod_company (
    name varchar(15000),
    id varchar(15000),
    movie varchar(15000)
)

"""

cursor.execute(query)

connection.commit()

In [ ]:
connection.rollback()

query = """

copy prod_company
from '/user/projects/project-3-richardshelby/data/raw/prodcomps.csv' delimiter ',' NULL '' csv header;

"""

cursor.execute(query)

connection.commit()

In [ ]:
rollback_before_flag = True
rollback_after_flag = True

query = """

select array_agg(name) as production_company,
       movie
from prod_company
group by movie

"""

my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

In [ ]:
connection.rollback()

query = """

drop table if exists lang_spoken

"""

cursor.execute(query)

connection.commit()

In [ ]:
connection.rollback()

query = """

create table lang_spoken (
    iso_639_1 varchar(8000),
    name varchar(8000),
    movie varchar(8000)
)

"""

cursor.execute(query)

connection.commit()

In [ ]:
connection.rollback()

query = """

copy lang_spoken
from '/user/projects/project-3-richardshelby/data/raw/spokenlangs.csv' delimiter ',' NULL '' csv header;

"""

cursor.execute(query)

connection.commit()

In [ ]:
rollback_before_flag = True
rollback_after_flag = True

query = """

select array_agg(name) as languages,
       movie
from lang_spoken
group by movie

"""

my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

In [180]:
rollback_before_flag = True
rollback_after_flag = True

query = """
with 

ep as (
    select array_agg(name) as executive_producer,
           movie
    from crews
    where department = 'Production' and job = 'Executive Producer'
    group by movie),

cp as (
    select array_agg(name) as original_composer,
           movie
    from crews
    where department = 'Sound' and job = 'Original Music Composer'
    group by movie
    ),

w as (
    select array_agg(name) as writer,
           movie
    from crews
    where department = 'Writing' and job = 'Writer'
    group by movie
    ),

dp as (
    select array_agg(name) as director_photography,
           movie
    from crews
    where department = 'Camera' and job = 'Director of Photography'
    group by movie
    ),
    
pcomp as (
    select array_agg(name) as production_company,
           movie
    from prod_company
    group by movie
    ),

pcont as (
    select array_agg(name) as production_country,
           movie
    from prod_country
    group by movie
    ),
    
sl as (
    select array_agg(name) as languages,
           movie
    from lang_spoken
    group by movie
    ),

m as (
    select * 
    from movies
    where (budget <> '0') and (budget <> '') and (genres <> '') and (revenue <> '0') and (revenue <> '') 
           and (vote_count <> '0') and (vote_count <> '') and (director_ <> '') and (cast_ <> '') 
           and (release_date <> '') and (runtime <> '0') and (runtime <> '') 
)

select m.title as title,
       m.budget::numeric as budget,
       m.genres as genres,
       m.id as id,
       m.keywords as keywords,
       m.overview as overview,
       m.popularity::numeric as popularity,
       m.vote_average::numeric as vote_average,
       m.vote_count::numeric as vote_count,
       m.cast_ as cast,
       m.director_ as director,
       ep.executive_producer as executive_producer,
       w.writer as writer, 
       cp.original_composer as original_music_composer,
       dp.director_photography as director_photography,
       pcont.production_country as production_country,
       pcomp.production_company as production_company,
       sl.languages as languages
from m
left join ep 
    on m.title = ep.movie
left join w 
    on m.title = w.movie
left join cp 
    on m.title = cp.movie
left join dp 
    on m.title = dp.movie
left join pcont 
    on m.title = pcont.movie
left join pcomp 
    on m.title = pcomp.movie
left join sl 
    on m.title = sl.movie
group by title,budget,genres,id,keywords,overview,popularity,vote_average,vote_count,cast_,director,executive_producer,writer,original_music_composer,director_photography,production_country,production_company,languages
having (count(*) < 2) 

"""

my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

,title,budget,genres,id,keywords,overview,popularity,vote_average,vote_count,cast,director,executive_producer,writer,original_music_composer,director_photography,production_country,production_company,languages
0,102 Dalmatians,85000000,Comedy Family,10481,london england prison release from prison wome...,Get ready for a howling good time as an all ne...,9.895061,5.1,313,Glenn Close Ioan Gruffudd Alice Evans Tim McIn...,Kevin Lima,None,None,None,[Adrian Biddle],[United States of America],"[Walt Disney Pictures, Cruella Productions]",[English]
1,10 Cloverfield Lane,15000000,Thriller Science Fiction Drama,333371,kidnapping bunker paranoia basement survivalist,"After a car accident, Michelle awakens to find...",53.698683,6.8,2468,Mary Elizabeth Winstead John Goodman John Gall...,Dan Trachtenberg,None,None,None,[Jeff Cutter],[United States of America],"[Bad Robot, Spectrum Effects, Paramount Pictures]",[English]
2,10 Things I Hate About You,16000000,Comedy Romance Drama,4951,shakespeare sister high school cannabis deception,"Bianca, a tenth grader, has never gone on a da...",54.550275,7.3,1701,Heath Ledger Julia Stiles Joseph Gordon-Levitt...,Gil Junger,"[Seth Jaret, Jeffrey Chernov]","[Karen McCullah Lutz, Kirsten Smith]",[Richard Gibbs],[Mark Irwin],[United States of America],"[Jaret Entertainment, Mad Chance, Touchstone P...","[Français, English]"
3,10th & Wolf,8000000,Action Crime Drama Mystery Thriller,13197,undercover mafia mobster crime family,A former street tough returns to his Philadelp...,3.942464,6.3,24,James Marsden Brian Dennehy Leo Rossi Dennis H...,Robert Moresco,None,"[Robert Moresco, Allan Steele]",None,None,[United States of America],[Thinkfilm],[English]
4,127 Hours,18000000,Adventure Drama Thriller,44115,mountains despair adventure utah alone,The true story of mountain climber Aron Ralsto...,52.464877,7.0,2606,James Franco Kate Mara Amber Tamblyn Cl\u00e9m...,Danny Boyle,"[Cameron McCracken, Bernard Bellew, Fran\u00e7...",None,[A. R. Rahman],"[Enrique Chediak, Anthony Dod Mantle]","[United States of America, United Kingdom]","[Film4, Warner Bros., Everest Entertainment, P...",[English]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3218,Zombieland,23600000,Comedy Horror,19908,washington d.c. sister sister relationship pos...,Columbus has made a habit of running from what...,57.300674,7.2,3550,Jesse Eisenberg Woody Harrelson Emma Stone Abi...,Ruben Fleischer,"[Ryan Kavanaugh, Rhett Reese, Paul Wernick, Ez...","[Paul Wernick, Rhett Reese]",None,None,[United States of America],"[Pariah, Relativity Media, Columbia Pictures]",[English]
3219,Zookeeper,80000000,Comedy Romance Family,38317,talking animal scientist german accent ostrich...,A comedy about a zookeeper who might be great ...,27.462640,5.3,498,Kevin James Rosario Dawson Sylvester Stallone ...,Frank Coraci,None,None,None,None,[United States of America],"[Hey Eddie, Sony Pictures Releasing, Zookeeper...",[English]
3220,Zoolander,28000000,Comedy,9398,male model time magazine fashion show fashion ...,"Clear the runway for Derek Zoolander, VH1's th...",38.095800,6.1,1337,Ben Stiller Owen Wilson Christine Taylor Will ...,Ben Stiller,"[Lauren Zalaznick, Adam Schroeder, Joel Gallen]",None,[David Arnold],[Barry Peterson],"[United States of America, Germany]","[NPV Entertainment, Red Hour Films, VH1 Televi...",[English]
3221,Zoolander 2,50000000,Comedy,329833,stupidity sequel fashion male model fashion model,Derek and Hansel are modelling again when an o...,37.253774,4.7,797,Ben Stiller Owen Wilson Will Ferrell Pen\u00e9...,Ben Stiller,None,"[John Hamburg, Ben Stiller, Justin Theroux, Ni...",None,None,[United States of America],"[Red Hour Films, Scott Rudin Productions]",[English]
3222,Zoom,35000000,Family Fantasy Comedy,14113,superhero kids and family,Jack Shepard is an out-of-shape auto shop owne...,10.304172,4.9,135,Tim Allen Courteney Cox Chevy Chase Spencer Br...,Peter Hewitt,"[Trevor Engelson, Neil A. Machlis, Nick Osborne]",None,[Christophe Beck],[David Tattersall],[United States of America],"[Revolution Studios, Columbia Pictures]",[English]

In [ ]:
rollback_before_flag = True
rollback_after_flag = True

query = """

select *
from movies

"""
my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

In [ ]:
cleanmovies.to_csv("/user/projects/project-3-richardshelby/data/interim/cleanmovies.csv")

In [ ]:
my_read_csv_file("/user/projects/project-3-richardshelby/data/interim/cleanmovies.csv", limit = 10)

## Import code for cleanmovies.csv

In [ ]:
connection.rollback()

query = """

drop table if exists cleanmovies

"""

cursor.execute(query)

connection.commit()

In [ ]:
connection.rollback()

query = """

create table cleanmovies (
    index varchar(4000),
    title varchar(4000),
    budget varchar(4000),
    genres varchar(4000),
    id varchar(4000),
    keywords varchar(4000),
    overview varchar(4000),
    popularity varchar(4000),
    vote_average varchar(4000),
    vote_count varchar(4000),
    cast_ varchar(4000),
    director varchar(4000),
    executive_producer varchar(4000),
    writer varchar(4000),
    original_music_composer varchar(4000),
    director_photography varchar(4000),
    production_country varchar(4000),
    production_company varchar(4000),
    languages varchar(4000)  
)

"""

cursor.execute(query)

connection.commit()

In [ ]:
connection.rollback()

query = """

copy cleanmovies
from '/user/projects/project-3-richardshelby/data/interim/cleanmovies.csv' delimiter ',' NULL '' csv header;

"""

cursor.execute(query)

connection.commit()

In [179]:
rollback_before_flag = True
rollback_after_flag = True

query = """

select *
from cleanmovies

"""
my_select_query_pandas(query, rollback_before_flag, rollback_after_flag)

,index,title,budget,genres,id,keywords,overview,popularity,vote_average,vote_count,cast_,director,executive_producer,writer,original_music_composer,director_photography,production_country,production_company,languages
0,0,102 Dalmatians,85000000,Comedy Family,10481,london england prison release from prison wome...,Get ready for a howling good time as an all ne...,9.895061,5.1,313,Glenn Close Ioan Gruffudd Alice Evans Tim McIn...,Kevin Lima,None,None,None,['Adrian Biddle'],['United States of America'],"['Walt Disney Pictures', 'Cruella Productions']",['English']
1,1,10 Cloverfield Lane,15000000,Thriller Science Fiction Drama,333371,kidnapping bunker paranoia basement survivalist,"After a car accident, Michelle awakens to find...",53.698682999999996,6.8,2468,Mary Elizabeth Winstead John Goodman John Gall...,Dan Trachtenberg,None,None,None,['Jeff Cutter'],['United States of America'],"['Bad Robot', 'Spectrum Effects', 'Paramount P...",['English']
2,2,10 Things I Hate About You,16000000,Comedy Romance Drama,4951,shakespeare sister high school cannabis deception,"Bianca, a tenth grader, has never gone on a da...",54.550275,7.3,1701,Heath Ledger Julia Stiles Joseph Gordon-Levitt...,Gil Junger,"['Seth Jaret', 'Jeffrey Chernov']","['Karen McCullah Lutz', 'Kirsten Smith']",['Richard Gibbs'],['Mark Irwin'],['United States of America'],"['Jaret Entertainment', 'Mad Chance', 'Touchst...","['Français', 'English']"
3,3,10th & Wolf,8000000,Action Crime Drama Mystery Thriller,13197,undercover mafia mobster crime family,A former street tough returns to his Philadelp...,3.9424639999999997,6.3,24,James Marsden Brian Dennehy Leo Rossi Dennis H...,Robert Moresco,None,"['Robert Moresco', 'Allan Steele']",None,None,['United States of America'],['Thinkfilm'],['English']
4,4,127 Hours,18000000,Adventure Drama Thriller,44115,mountains despair adventure utah alone,The true story of mountain climber Aron Ralsto...,52.464877,7.0,2606,James Franco Kate Mara Amber Tamblyn Cl\u00e9m...,Danny Boyle,"['Cameron McCracken', 'Bernard Bellew', 'Fran\...",None,['A. R. Rahman'],"['Enrique Chediak', 'Anthony Dod Mantle']","['United States of America', 'United Kingdom']","['Film4', 'Warner Bros.', 'Everest Entertainme...",['English']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3218,3218,Zombieland,23600000,Comedy Horror,19908,washington d.c. sister sister relationship pos...,Columbus has made a habit of running from what...,57.300674,7.2,3550,Jesse Eisenberg Woody Harrelson Emma Stone Abi...,Ruben Fleischer,"['Ryan Kavanaugh', 'Rhett Reese', 'Paul Wernic...","['Paul Wernick', 'Rhett Reese']",None,None,['United States of America'],"['Pariah', 'Relativity Media', 'Columbia Pictu...",['English']
3219,3219,Zookeeper,80000000,Comedy Romance Family,38317,talking animal scientist german accent ostrich...,A comedy about a zookeeper who might be great ...,27.462640000000004,5.3,498,Kevin James Rosario Dawson Sylvester Stallone ...,Frank Coraci,None,None,None,None,['United States of America'],"['Hey Eddie', 'Sony Pictures Releasing', 'Zook...",['English']
3220,3220,Zoolander,28000000,Comedy,9398,male model time magazine fashion show fashion ...,"Clear the runway for Derek Zoolander, VH1's th...",38.0958,6.1,1337,Ben Stiller Owen Wilson Christine Taylor Will ...,Ben Stiller,"['Lauren Zalaznick', 'Adam Schroeder', 'Joel G...",None,['David Arnold'],['Barry Peterson'],"['United States of America', 'Germany']","['NPV Entertainment', 'Red Hour Films', 'VH1 T...",['English']
3221,3221,Zoolander 2,50000000,Comedy,329833,stupidity sequel fashion male model fashion model,Derek and Hansel are modelling again when an o...,37.253774,4.7,797,Ben Stiller Owen Wilson Will Ferrell Pen\u00e9...,Ben Stiller,None,"['John Hamburg', 'Ben Stiller', 'Justin Therou...",None,None,['United States of America'],"['Red Hour Films', 'Scott Rudin Productions']",['English']
3222,3222,Zoom,35000000,Family Fantasy Comedy,14113,superhero kids and family,Jack Shepard is an out-of-shape auto shop owne...,10.304172,4.9,135,Tim Allen Courteney Cox Chevy Chase Spencer Br...,Peter Hewitt,"['Trevor Engelson', 'Neil A. Machlis', 'Nick O...",None,['Christophe Beck'],['David Tattersall'],['United States of America'],"['Revolution Studios', 'Columbia Pictures']",['English']